; NFD testbed configuration

general
{
  user   nobody
  group  nogroup
}

log
{
  default_level INFO
}

tables
{
  cs_max_packets 65536

  strategy_choice
  {
    /  /localhost/nfd/strategy/best-route
    /localhost  /localhost/nfd/strategy/multicast
    /localhost/nfd  /localhost/nfd/strategy/best-route
    /ndn/broadcast  /localhost/nfd/strategy/multicast
  }
}

face_system
{
  unix
  {
    path /run/nfd.sock
  }

  tcp
  {
    listen   yes
    port     6363
    enable_v4  yes
    enable_v6  no
  }

  udp
  {
    listen      yes
    port        6363
    enable_v4   yes
    enable_v6   no
    mcast       no
  }
}

authorizations
{
  authorize
  {
    certfile any
    privileges
    {
      faces
      fib
      rib
      cs
      strategy-choice
    }
  }
}

rib
{
  localhost_config_file_authority /
}
